swagger: "2.0"
info:
  version: 1.0.0
  title: AGID forms
  description: AGID forms.
host: localhost
basePath: /api/v1
paths: {}
schemes:
  - https
security:
  - Bearer: []
definitions:
  EmailAddress:
    type: string
    format: email
    example: foobar@example.com
  FiscalCode:
    type: string
    description: User's fiscal code.
    format: FiscalCode
    x-import: italia-ts-commons/lib/strings
    example: SPNDNL80R13C555X
