version: "3"

services:

  agid-forms-backend:
    image: node:8.11.3-alpine
    volumes:
      - .:/usr/src/app
    command: ["yarn", "hot-reload"]
    working_dir: "/usr/src/app"

  agid-forms-backend-dispatcher:
    image: node:8.11.3-alpine
    volumes:
      - .:/usr/src/app
    working_dir: "/usr/src/app"

  agid-forms-backend-worker-01:
    image: node:8.11.3-alpine
    volumes:
      - .:/usr/src/app
    working_dir: "/usr/src/app"

  agid-forms-backend-worker-02:
    image: node:8.11.3-alpine
    volumes:
      - .:/usr/src/app
    working_dir: "/usr/src/app"
