version: "3"

services:

  redis:
    image: bitnami/redis:5.0
    env_file: 
      - .env
    ports:
      - "6379"
    networks:
      - app-tier
    volumes:
      - /data/redis:/bitnami/redis/data
    restart: unless-stopped

  redis-commander:
    image: rediscommander/redis-commander
    env_file: 
      - .env
    environment:
      - PORT=${REDIS_PORT}
    ports:
      - "8081"
    networks:
      - app-tier
    depends_on:
      - redis
    restart: unless-stopped

  postgresql:
    image: bitnami/postgresql:11
    env_file: 
      - .env
    ports:
      - '5432'
    networks:
      - app-tier
    volumes:
      - /data/postgresql:/bitnami/postgresql
      - /data/wal-logs:/bitnami/wal-logs
      - ./scripts/ipa-import-local.sh:/ipa-import-local.sh
    restart: unless-stopped

  hasura:
    image: hasura/graphql-engine:v1.0.0-beta.3
    labels:
      - traefik.enable=true
      - traefik.frontend.rule=Host:${HASURA_HOST}
      - traefik.docker.network=app-tier
    env_file:
      - .env
    ports:
      - "8080"
    networks:
      - app-tier
    depends_on:
      - postgresql
    restart: unless-stopped

  agid-forms-backend:
    # image: docker.io/gunzip/agid-forms-backend:${BACKEND_VERSION}
    image: agid-forms-backend:local
    env_file: 
      - .env
    build:
      context: .
      args:
        - HASURA_GRAPHQL_ENDPOINT
        - HASURA_GRAPHQL_ADMIN_SECRET
    labels:
      - traefik.enable=true
      - traefik.frontend.rule=Host:${BACKEND_HOST}
      - traefik.docker.network=app-tier
    ports:
      - "80"
    command: ["yarn", "start"]
    networks:
      - app-tier
    depends_on:
      - hasura
      - redis
      # to get graphql endpoint with https
      - traefik
    restart: unless-stopped

  agid-forms-backend-processor:
    # image: docker.io/gunzip/agid-forms-backend:${BACKEND_VERSION}
    image: agid-forms-backend:local
    env_file: 
      - .env
    command: ["yarn", "run-processor"]
    networks:
      - app-tier
    depends_on:
      - agid-forms-backend
    restart: unless-stopped

  traefik:
    image: traefik:v1.7
    command: |-
      --api
      --api.dashboard=true
      --debug=false
      --loglevel=ERROR
      --retry
      --defaultentrypoints=http,https
      --entryPoints='Name:traefik Address::${TRAEFIK_DASHBOARD_PORT} Auth.Basic.Users:${TRAEFIK_DASHBOARD_USER}:${TRAEFIK_DASHBOARD_PASSWORD}'
      --entryPoints='Name:http Address::80 Redirect.EntryPoint:https'
      --entryPoints='Name:https Address::443 TLS'
      --docker
      --docker.endpoint="unix:///var/run/docker.sock"
      --docker.domain=${TRAEFIK_DOMAIN}
      --docker.watch=true
      --docker.exposedbydefault=false
      --acme
      --acme.email=${TRAEFIK_ACME_EMAIL} 
      --acme.entrypoint=https
      --acme.httpchallenge.entrypoint=http
      --acme.storage=acme.json
      --acme.onhostrule=true
    labels:
      - traefik.docker.network=app-tier
    env_file: 
      - .env
    ports:
      - 80:80
      - 443:443
      - ${TRAEFIK_DASHBOARD_PORT}:${TRAEFIK_DASHBOARD_PORT}
    networks:
      - app-tier
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /data/traefik/acme.json:/acme.json
    restart: unless-stopped

networks:
  app-tier:
    driver: bridge
    driver_opts:                         
      com.docker.network.driver.mtu: 1450
