version: "3.4"

services:
  minio:
    image: bitnami/minio:2019.10.12-r3
    env_file:
      - .env
    ports:
      - ${MINIO_SERVER_PORT_NUMBER}
    networks:
      - app-tier
    volumes:
      - /data/minio:/data
    restart: unless-stopped

  redis:
    image: bitnami/redis:5.0
    env_file:
      - .env
    ports:
      - ${REDIS_PORT}
    networks:
      - app-tier
    volumes:
      - /data/redis:/bitnami/redis/data
    restart: unless-stopped

  redis-commander:
    image: rediscommander/redis-commander
    env_file:
      - .env
    environment:
      - PORT=${REDIS_PORT}
    ports:
      - ${REDIS_COMMANDER_PORT}
    networks:
      - app-tier
    depends_on:
      - redis
    restart: unless-stopped

  postgresql:
    image: bitnami/postgresql:11
    env_file:
      - .env
    ports:
      - ${POSTGRESQL_PORT}
    networks:
      - app-tier
    volumes:
      - /data/postgresql:/bitnami/postgresql
      - /data/wal-logs:/bitnami/wal-logs
      - /data/db-backups:/db-backups
      - ./scripts/ipa-import-local.sh:/ipa-import-local.sh
      - ./scripts/backup-db.sh:/backup-db.sh
      - ./scripts/cleanup-hasura-events.sh:/cleanup-hasura-events.sh
    restart: unless-stopped

  hasura:
    image: hasura/graphql-engine:v1.0.0-beta.9
    labels:
      - traefik.enable=true
      - traefik.frontend.rule=Host:${HASURA_HOST}
      - traefik.port=${HASURA_PORT}
      - traefik.docker.network=app-tier
    env_file:
      - .env
    ports:
      - ${HASURA_PORT}
    networks:
      - app-tier
    depends_on:
      - postgresql
    restart: unless-stopped

  agid-forms-backend:
    image: agid-forms-backend:local
    env_file:
      - .env
    build:
      context: .
      network: ${COMPOSE_PROJECT_NAME}_app-tier
      args:
        - HASURA_GRAPHQL_ENDPOINT
        - HASURA_GRAPHQL_ADMIN_SECRET
    labels:
      - traefik.enable=true
      - traefik.frontend.rule=Host:${BACKEND_HOST}
      - traefik.port=${BACKEND_PORT}
      - traefik.docker.network=app-tier
    ports:
      - ${BACKEND_PORT}
    command: ["yarn", "start"]
    networks:
      - app-tier
    depends_on:
      - hasura
      - redis
      # to get graphql endpoint with https
      - traefik
    restart: unless-stopped

  agid-forms-backend-processor:
    image: agid-forms-backend:local
    env_file:
      - .env
    command: ["yarn", "run-processor"]
    networks:
      - app-tier
    depends_on:
      - agid-forms-backend
    restart: unless-stopped

  agid-forms-backend-uploads:
    image: agid-forms-backend:local
    env_file:
      - .env
    labels:
      - traefik.enable=true
      - traefik.frontend.rule=Host:${UPLOAD_SERVER_HOST}
      - traefik.port=${UPLOAD_SERVER_PORT}
      - traefik.docker.network=app-tier
    ports:
      - ${UPLOAD_SERVER_PORT}
    command: ["yarn", "run-uploads"]
    networks:
      - app-tier
    depends_on:
      - agid-forms-backend
    restart: unless-stopped

  traefik:
    image: traefik:v1.7
    command: |-
      --api
      --api.dashboard=true
      --debug=false
      --loglevel=ERROR
      --retry
      --defaultentrypoints=http,https
      --entryPoints='Name:traefik Address::${TRAEFIK_DASHBOARD_PORT} Auth.Basic.Users:${TRAEFIK_DASHBOARD_USER}:${TRAEFIK_DASHBOARD_PASSWORD}'
      --entryPoints='Name:http Address::80 Redirect.EntryPoint:https'
      --entryPoints='Name:https Address::443 TLS'
      --docker
      --docker.endpoint="unix:///var/run/docker.sock"
      --docker.domain=${TRAEFIK_DOMAIN}
      --docker.watch=true
      --docker.exposedbydefault=false
      --acme
      --acme.email=${TRAEFIK_ACME_EMAIL} 
      --acme.entrypoint=https
      --acme.httpchallenge.entrypoint=http
      --acme.storage=acme.json
      --acme.onhostrule=true
    labels:
      - traefik.docker.network=app-tier
      - traefik.frontend.headers.STSPreload=true
      - traefik.frontend.headers.STSSeconds=31536000
    env_file:
      - .env
    ports:
      - 80:80
      - 443:443
      - ${TRAEFIK_DASHBOARD_PORT}:${TRAEFIK_DASHBOARD_PORT}
    networks:
      - app-tier
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /data/traefik/acme.json:/acme.json
    restart: unless-stopped

networks:
  app-tier:
    driver: bridge
    driver_opts:
      com.docker.network.driver.mtu: 1450
