version: "3"

services:

  agid-forms-backend:
    image: node:8.11.3-alpine
    volumes:
      - .:/usr/src/app
    command: ["yarn", "hot-reload"]
    working_dir: "/usr/src/app"

  agid-forms-backend-processor:
    image: node:8.11.3-alpine
    volumes:
      - .:/usr/src/app
    command: ["yarn", "run-processor:reload"]
    working_dir: "/usr/src/app"
