version: "2"

services:
  agid-forms-backend:
    command: ["yarn", "hot-reload"]
    container_name: agid-forms-backend
    environment:
      - NODE_ENV=dev
    expose:
      - "443"
    ports:
      - "443:443"
    image: node:8.9.4-alpine
    volumes:
      - ".:/usr/src/app"
      - "./certs:/usr/src/app/certs"
    working_dir: "/usr/src/app"

  redis:
    container_name: redis
    image: wodby/redis:3.2-2.1.5
    environment:
      REDIS_TIMEOUT: 300
      REDIS_TCP_KEEPALIVE: 60
      REDIS_MAXMEMORY: 182m
