const path = require("path");
const gulp = require("gulp");
const textSimple = require("gulp-text-simple");
const rename = require("gulp-rename");
const mjml2html = require("mjml");
const prettier = require("gulp-prettier");

const TYPESCRIPT_SOURCE_DIR = "src";
const TEMPLATES_SOURCE_DIR = "templates/mjml";
const TEMPLATES_SOURCE = `${TEMPLATES_SOURCE_DIR}/*.mjml`;
const TEMPLATES_OUTPUT_DIR = `${TYPESCRIPT_SOURCE_DIR}/templates/html`;

const toMjml = content => {
  const html = mjml2html(content, { minify: true }).html;
  return `  // DO NOT EDIT THIS FILE
            // this file was auto generated by gulp generate:templates
            export const withDefaultEmailTemplate = (
              titleText: string,
              senderOrganizationName: string,
              senderServiceName: string,
              contentHtml: string): string 
            => (\`${html}\`);
          `;
};

/**
 * Generate Typescript template files from mjml (https://mjml.io/).
 */
gulp.task("generate:templates", () => {
  return gulp
    .src(TEMPLATES_SOURCE)
    .pipe(textSimple(toMjml)())
    .pipe(prettier())
    .pipe(rename(filepath => (filepath.extname = ".ts")))
    .pipe(gulp.dest(TEMPLATES_OUTPUT_DIR));
});
