#
# The app proxy
#
---
#
# Deploy the pods
#
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: backend
  namespace: default
  labels:
    app: backend
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 50%
      maxSurge: 1
  revisionHistoryLimit: 10
  template:
    metadata:
      name: backend
      namespace: default
      labels:
        app: backend
    spec:
      containers:
      - image: docker.io/gunzip/agid-forms-backend:0.2.7
        name: backend
        ports:
        - name: http-port
          containerPort: 80
        env:
        - name: "AUTHENTICATION_BASE_PATH"
          value: ""
        - name: "NODE_ENV"
          value: "development"
        - name: "REDIS_URL"
          value: "redis-master"
        - name: "REDIS_PORT"
          value: "6379"
        - name: "WEBHOOK_USER_LOGIN_BASE_URL"
          value: "http://backend"
        - name: "USER_ROLE_ID"
          value: "31438e54-87fb-469c-acc0-21480e59a22a"
        - name: "JSONAPI_BASE_URL"
          value: "https://drupal.danilospinelli.com/jsonapi"
        - name: "ELASTICSEARCH_URL"
          value: "http://es:9200"
        - name: "ORGANIZATION_NAME"
          value: "AGID"
        - name: "SERVICE_NAME"
          value: "Agenzia per l'Italia Digitale"
        - name: "AUTHMAIL_FROM"
          value: "no-reply@agid.gov.it"
        - name: "AUTHMAIL_REPLY_TO"
          value: "no-reply@agid.gov.it"
          # TODO: delete the following line
        - name: "AUTHMAIL_TEST_ADDRESS"
          value: "danilo.spinelli@agid.gov.it"
        - name: "SMTP_CONNECTION_URL"
          valueFrom:
            secretKeyRef:
              name: backend-secrets
              key: smtp_connection_url
        - name: "WEBHOOK_JWT_SECRET"
          valueFrom:
            secretKeyRef:
              name: backend-secrets
              key: webhook_jwt_secret
        - name: "JWT_SECRET"
          valueFrom:
            secretKeyRef:
              name: backend-secrets
              key: jwt_secret
        - name: "REDIS_PASSWORD"
          valueFrom:
            secretKeyRef:
              name: backend-secrets
              key: redis_password
        - name: "TOKEN_DURATION_IN_SECONDS"
          # 30 days
          value: "2592000"
        livenessProbe:
          httpGet:
            path: "/ping"
            port: 80
          initialDelaySeconds: 30
          timeoutSeconds: 5
          periodSeconds: 10
          failureThreshold: 5
        resources:
          limits:
            cpu: 500m
            memory: 2Gi
          requests:
            cpu: 200m
            memory: 256Mi

---
#
# A service exposing the app to the cluster.
#
apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: default
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 80
