apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: hasura
    hasuraService: custom
  name: hasura
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hasura
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hasura
    spec:
      containers:
      - image: hasura/graphql-engine:v1.0.0-beta.2
        imagePullPolicy: IfNotPresent
        name: hasura
        env:
        - name: EVENTS_WEBHOOK_URL
          value: "https://backend.danilospinelli.com/api/v1/graphql/events"
        - name: HASURA_WEBHOOK_SECRET
          valueFrom:
            secretKeyRef:
              name: backend-secrets
              key: hasura_webhook_secret
        - name: HASURA_GRAPHQL_UNAUTHORIZED_ROLE 
          value: "anonymous"
        - name: HASURA_GRAPHQL_ENABLE_CONSOLE
          value: "false"
        - name: HASURA_GRAPHQL_JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: backend-secrets
              key: hasura_jwt_secret
        - name: HASURA_GRAPHQL_ADMIN_SECRET
          valueFrom:
            secretKeyRef:
              name: backend-secrets
              key: hasura_admin_password
        - name: HASURA_GRAPHQL_DATABASE_URL
          # value: postgres://username:password@hostname:port/dbname
          valueFrom:
            secretKeyRef:
              name: backend-secrets
              key: postgres_connection_url
        - name: HASURA_GRAPHQL_ENABLE_CONSOLE
          value: "true"
        ports:
        - containerPort: 8080
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 2Gi
          requests:
            cpu: 200m
            memory: 256Mi
