apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.version: 1.17.0 (a74acad)
  creationTimestamp: null
  labels:
    io.kompose.service: redis
  name: redis
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: redis
    spec:
      containers:
      - env:
        - name: REDIS_MAXMEMORY
          value: 182m
        - name: REDIS_TCP_KEEPALIVE
          value: "60"
        - name: REDIS_TIMEOUT
          value: "300"
        image: wodby/redis:3.2-2.1.5
        name: redis
        resources: {}
      restartPolicy: Always
status: {}
